AfroPython/afropython-site

.github/PULL_REQUEST_TEMPLATE.md

Adicionar ao projeto uma proposta de para ser utilizada nos PRs
Adicionei um arquivo chamado `PULL_REQUEST_TEMPLATE.md` na pasta `.github`
Só poderemos ver isso em ação quando isso aqui for mergeado. :(
@Amandasv @zalbamonteiro

Adiciona uma proposta de Pull Request template

---

package.json

deixar o gulp configurado como localmente
mudanças de caminho da dependência do gulp no package.json 
npm start
@lipemorais e @Amandasv

ajuste de dependência do gulp no json

---

src/scss/4.components/_intro.scss

Responsivizar o fotao
Eu estou arrumando as fontes para que se adaptem corretamente.
Utilize o inspector do css para ver como está ficando.
@Amandasv @zalbamonteiro @nyan07
**TODO**

Arrumar o tamanho da fonte do título

---

public/index.html
src/scss/3.objects/_grid.scss
src/scss/4.components/_about-event.scss
src/scss/4.components/_footer.scss

Criei a session sobre o evento com o conteúdo da wiki, tentei deixar harmonioso com o restante do site, mas o layout está sujeito a modificações e sugestões. Já está responsiva essa parte também
liberar a sessão sobre o evento
html e css para a sessão e criação de classes para grid
npm start e reload na pagina
@lipemorais e @Amandasv

session about-event

---

README.md

Adicionei o ícone do waffle no readme.
Adicionar o ícone bonitinho do Waffle. Já tinha uma issue cadastrada e já fechada para isso, mas estava somente o link, sem o badge ;)
Peguei o link lá nas configurações do Waffle e colei no readme
Pode ser testado na página inicial do repositório, trocando para o branch **asv-waffle**
__@lipemorais @zalbamonteiro__

Add waffle icone

---

public/index.html

fix #20 
O link de contato no rodapé estava sem o target (href).
Coloquei o link do nosso email.
Ao clicar em `Entre em contato através do **afropython@gmail.com** `, deve redirecionar para o client de email.
@lipemorais  @zalbamonteiro

Arruma o link de contato que estava no rodape

---

public/index.html

Adicionar o script do Google Analytics para que possamos entender o impacto do nosso projeto e o acesso ao site. fixes #25
Adicionei o script do Google no index.html.
Não sei como testar. :'(
@Amandasv @zalbamonteiro

Google Analytics no site do Afro Python

---

public/index.html

Não mostrar a data do evento momentaneamente
Comentei a data ;)
A data na intro do site não deve estar aparecendo.
@lipemorais @zalbamonteiro

Comenta a data do evento

---

public/index.html
src/js/2-main.js
src/scss/1.config/_variables.scss
src/scss/2.base/_scaffold.scss
src/scss/4.components/_code-conduct.scss
src/scss/4.components/_intro.scss
src/scss/4.components/_section-forms.scss
src/scss/style.scss

Adicionar os links de participantes e treinadores
Fix #36 
- Criei uma nova sessão, nesse coloquei um pequeno textinho e adicionei os links dos formulários
- Ajustei o tamanho e cor dos paragráfos padrões
- Mudei o acionamento da modal, anteriormente estava como id, e coloquei como class, assim poderá ser chamado por outros componentes também. 
Fazendo o pull para o branch formulários. Deverá ter uma nova sessão, juntamente com os links para preenchimento. (Clicar nos links e confirmar se são os corretos)
@lipemorais @zalbamonteiro

Formularios

---

public/index.html

Atualização de algumas meta_tags conforme depurador do facebook
Atualizei as tags:
- og:image 
- og:type
- e o valor absoluto para og:ur
Somente após fazer o deploy para confirmar
@anaschwendler @lipemorais

update meta_tags with facebook recommendations

---

Code_of_Conduct.md

Traduz o código de conduta para o Inglês.
Criado um arquivo em Markdown.
Basta clicar no arquivo.
Qualquer pessoa da equipe.
**TODO**

Fixes #45 – Code of Conduct [en]

---

.github/PULL_REQUEST_TEMPLATE.md

O propósito desse PR é arrumar um pequeno problema no PR template com o espaçamento.
Eu só adicionei o espaçamento para fica certinho o TODO ali.
Só olhar o PR que dá para ver que ficou certinho.
@Amandasv @anaschwendler @carolmoers

Corrigi o Pull Request Template na parte do TODO

---

public/index.html
src/scss/4.components/_code-conduct.scss

1. Corrigir o alinhamento do texto para dispositivos com tela pequena.
1. Corrigir o espaçamento do texto.
1. Removido a classe CSS que centralizava o texto.
1. Removido o espaço extra na pontuação / acrescentado espaço após a pontuação.
Executar o ambiente de desenvolvimento e utilizar o "Responsive  Design Mode" do navegador para dispositivos com tela pequena. 
Qualquer pessoa que possa rodar o ambiente de desenvolvimento.

Fixes #21 – Alinhamento do texto em modal

---

README_EN.md

Issue #44 
Tradução completa do arquivo README.md para o Inglês
Basta clicar no arquivo.
Qualquer pessoa.
**Nota**
https://github.com/AfroPython/afropython-site/issues/44#issuecomment-338030819 - Contudo, visto que o README é a "porta de entrada" para novas contribuições e há uma versão em inglês do código de conduta, seria interessante também ter esse arquivo traduzido.

Fixes #44 – Add english version of README

---

Code_of_Conduct.md

Issue #51 
Add trecho faltante no arquivo Code_of_Conduct.md
Basta clicar no arquivo.
Qualquer pessoa.

Fixes #51 – Add missing text to code of conduct

---

public/index.html
src/scss/4.components/_endereco.scss
src/scss/style.scss

Adicionar o endereço do local (Faculdade Senac)
Close #41 
Adicionei o endereço e o mapa do local.
Fazendo pull do branch `local_evento` e verificando se aparece o endereço e mapa
@pedrro @lipemorais @zalbamonteiro @anaschwendler

Endereço do evento

---

.gitignore
public/index.html

Adicionar hora do evento e remover links de inscrições
Atualização do site
RUN IT!
@zalbamonteiro @Amandasv @lipemorais

Encerra inscrições no site - Adiciona hora do evento

---

public/index.html

Colocar tanto data quanto hora no **quando**
Reorganizei para ficar certinho ali.
Só rodar, ver como ficou e olha o diff.
@Amandasv @zalbamonteiro @pedrro

Coloca a data e a hora na mesma linha

---

public/index.html

Isto aqui é só uma sugestão para facilitar a revisão do seu Pull Request e fazer com que ele seja aprovado mais rápido. :)
colocar o link para a visualização de fotos do evento
criei um section nova com um title, text e link em formato de botão com o label "ver fotos"
fazer pull da PR, rodar gulp e vsualizar se o botão aparece e clicar e ver se ela irá redirecionar para as fotos.
@Amandasv , @lipemorais , @pedrro , @thayseonofrio

inser link para ver fotos do evento

---

public/index.html

retirar as datas do banner do evento passado
retirei os textos que estava essas informações
pull da PR, gulp e visualizar se no banner principal foram retiradas as datas.
@Amandasv , @lipemorais , @pedrro

retirei data do evento passado do banner principal

---

public/index.html

Remover a sessão de inscrições para o Palmares do site.
Deletei o HTML responsável por mostrar isso.
`npm start` e ver que a sessão não se encontra mais lá
@zalbamonteiro @Amandasv @pedrro

Remove a sessão de inscrição dos participantes criado para o Palmares

---

public/index.html

Remover a divulgação do evento Palmares do site.
Deletar as partes que refere-se ao evento que já passou.
`npm start`e verificar se não há mais divulgação ao evento Palmares (já finalizado).
Qualquer pessoa interessada.

Issue#72: Remoção da divulgação do evento Palmares

---

public/index.html

__Remover as empresas apoiadoras do evento Palmares__
__Deleção dos apoiadores do evento palmares do site__
__Executar e ver se está tudo certo__
__Qualquer pessoa interessada__

Remoção dos apoiadores do palmares

---

.dockerignore
Dockerfile
Makefile
README.md
README_EN.md
nginx.conf

- Dockerfile pro site! #40 - Imagem do site gerado e disponibilizado como um container (`~9MB`)
- Adicionado `Dockerfile` com instruções de buid
- Adicionado `Makefile` para facilitar operações comuns a operações relacionados ao container (build,push e info)
- Publicado o resultado em https://hub.docker.com/r/afropython/afropython-site
:exclamation: **Requer Docker**
1.  Build da imagem:
`docker build -t afropython/afropython-site -f Dockerfile .`
2.  Prover container ;
`docker run --rm -dt -p 8080:80 --name afropython afropython/afropython-site`
3.  Acessar http://localhost:8080 e verificar o resulado;
Engenheiros …

Adicionado Docker ao projeto

---

src/index.html

Adicionar botões com direcionamento para os formulários de participantes, treinadores e patrocinadores.
Rodar localmente.
Todos
**Imagem da alteração**

Adiciona links para formulários de treinadores e participantes

---

src/index.html

Isto aqui é só uma sugestão para facilitar a revisão do seu Pull Request e fazer com que ele seja aprovado mais rápido. :)
Adicionei o local do evento do AfroPython do dia 24 de novembro <3
Editei o Index.html adicionando uma sessão com um iframe do mapa da PUC.
Só rodando pra ver xD
Pedro :)

Adicionando local ao evento do AfroPython

---

package-lock.json
package.json

Isto aqui é só uma sugestão para facilitar a revisão do seu Pull Request e fazer com que ele seja aprovado mais rápido. :)
__Coloque aqui como isso ajuda o projeto__
__Explique aqui o que foi feito para que isso funcionasse__
__Escreve aqui como a gente poderia testar e ver isso funcionando__
__Quem são as melhores pessoas para revisar esse PR?__
**TODO**
__Caso tenha algo que ainda precisa ser feito crie uma lista aqui__

move jquery e autoprefixer para dependencias

---

src/index.html
src/js/main.js

Adicionar o link do site do evento AfroPython Conf no site
Na primeira sessão da página foi adicionado um banner do evento com as informações da data e do local
Depois que clonar e executar o projeto (seguir as instruções do arquivo README.md):
1 - verificar que existe uma banner e as informações da data e local do evento na primeira sessão da página;
2 - clicar no banner ou, na data/local do evento, e confirmar que uma nova aba irá se abrir com o endereço do site do evento do AfroPython Conf (http://afropythonconf.org/)
Qualquer pessoa que contribui com o projeto

Adicionar o link do site do evento do AfroPython Conf no site do AfroPython

---

src/js/main.js

Por conta do Uglyfy, durante o deploy o arquivo src/js/main.js não compila e bloqueia a operação.
Reverter alterações no arquivo src/js/main.js
O arquivo foi voltado ao estado anterior
Executar o comando `npm build` e verificar que nenhum erro aparece
Qualquer pessoa com acesso ao repositório

Revertendo o arquivo por conta do Uglyfy

---

src/index.html
src/js/main.js

Remover as informações do evento AfroPython Conf do site
Remover o bloco de código que exibe as informações do evento
Executar o projeto localmente (vide informações no arquivo README.md) e, verificar que não é  exibida nenhuma informação referente ao AfroPython Conf no banner principal do site
Qualquer pessoa com acesso ao repositório

Remove o banner do AfroPython Conf
